# Site settings
title: Resources from mygov.scot
email: feedback.mygov@gov.scot
description: These resources have been made available to help deliver clear content and to guide you in building digital services that will appear on mygov.scot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://resources.mygov.scot" # the base hostname & protocol for your site
mygov_twitter_username: mygovscot
mygov_twitter_url: https://www.twitter.com/mygovscot
mygov_site_url: https://www.mygov.scot/
mygov_blog_url: https://inside.mygov.scot/
mygov_blog_title: inside.mygov.scot
mygov_description:
github_username: scottishgovernment
github_url: https://github.com/scottishgovernment/
github_sg_site_url: https://scottishgovernment.github.io
dts_twitter_username: DTS
dts_twitter_url: https://twitter.com/cg_dts
dts_email: cgdts@gov.scot
dts_telephone_number: 0141 242 0109
dts_site_url:
dts_blog_url: https://blogs.gov.scot/digital/category/digital-public-services/digital-transformation-service/
dts_blog_title: Digital Transformation Service
dts_description: The Digital Transformation Service (DTS) can help Central Government organisations design programmes that deliver Digital Services that meet citizen needs.
gtm_code: GTM-M2JDBWP
sass:
    sass_dir: assets/_scss

# Build settings
markdown: kramdown

# Collections
collections:
  additional:
    output: true
    permalink: /standards/:name/
    parent: home
  services:
    output: true
    permalink: /services/:name/
    parent: home
  criterion:
    output: true
    permalink: /criterion/:name/
    parent: home
  assessments:
    output: true
    permalink: /assessments/:name/
    parent: home
  guidelines:
    output: true
    permalink: /guidelines/:name/
    parent: home
  prototypes:
    output: true
    permalink: /prototypes/:name/
    parent: home
  jobs:
    output: true
    permalink: /jobs/:name/
    parent: home
  examples:
    output: true

# Default values
defaults:
  - scope:
      path: ""
      type: additional
    values:
      parent: home
  - scope:
      path: ""
      type: services
    values:
      parent: home
  - scope:
      path: ""
      type: criterion
    values:
      parent: home
  - scope:
      path: ""
      type: assessments
    values:
      parent: home
  - scope:
      path: ""
      type: guidelines
    values:
      parent: home
  - scope:
      path: ""
      type: prototypes
    values:
      parent: home
  - scope:
      path: ""
      type: jobs
    values:
      parent: home
  - scope:
      path: ""
      type: examples
    values:
      sitemap: false

# Gems required for plugins
gems:
  - jekyll-sitemap
